version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: airportart_db
            MYSQL_USER: user
            MYSQL_PASSWORD: user_password
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network

    directus:
        image: directus/directus:latest
        container_name: directus-container
        environment:
            DB_CLIENT: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: airportart_db
            DB_USER: user
            DB_PASSWORD: user_password
            ADMIN_EMAIL: admin@example.com
            ADMIN_PASSWORD: admin_password
            CORS_ENABLED: "true"
            CORS_ORIGIN: "*"
        ports:
            - "8055:8055"
        depends_on:
            - mysql
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin-container
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root_password
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - app-network

    flyway:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: flyway-container
        environment:
            FLYWAY_URL: jdbc:mysql://mysql:3306/airportart_db
            FLYWAY_USER: user
            FLYWAY_PASSWORD: user_password
            FLYWAY_LOCATIONS: filesystem:/flyway/sql
            FLYWAY_BASELINE_ON_MIGRATE: "true"
        volumes:
            - ./migrations:/flyway/sql
        networks:
            - app-network

volumes:
    mysql-data:


networks:
    app-network:
